### ISSUE TITLE
Add support for uploading large files (>1GB)

### ISSUE THREAD

**Issue by getvictor** [phallstrom/el_finder#19]
How hard is it to add support for uploading very large files?

I tried to upload a 40GB file and got the following on the webrick backend:
ERROR NoMemoryError: failed to allocate memory

**Comment by ParthBarot-BoTreeConsulting** [comment]
@getvictor @dup2 Sorry to add this here, but I am stuck on this. 

For my Nginx+Rails app setup, I have used the nginx upload module to fix this "2 GB upload" issue. but it is not able to handle total of 1 GB files, and also not when multiple users trying the same - 1 GB total from each user.

My question is, do we need more RAM/CPU for this? Is there anything which says, "For 1 GB file upload, you need X GB of RAM on cloud server" and so on? OR is it a trial and error approch?

For now, I am having 4GB RAM on this nginx+Rails server, do you think moving it to 8GB/16GB RAM should help fixing the 2GB upload?

Thanks

**Comment by dup2** [comment]
For the upload_module, it's not a RAM issue - the file gets decoded and written to the filesystem on the fly while processing the upload with a small buffer only. We successfully upload 10GB files this way (nginx and unicorn backends).

If you are having memory issues, it might be on the rails side. Do you load the file in memory to process it? 
I'd recommend to debug this separately: Ensure the upload via nginx works and check the temporary file you are getting in the backend and when this works without memory issues debug your rails application processing the uploaded file.

**Comment by ParthBarot-BoTreeConsulting** [comment]
@dup2 Thanks for your quick reply! No, I am not sure it's a RAM issue, I just want to confirm it.

The Nginx upload module is working fine, it uploads the file with random name in the temp folder we have set. And then we forward only the file details (size/name/path) to the unicorn server and able to see the request params as well in the Rails logs.

The issue is, when we upload total say 50/100 files, making the total size ~1 GB, it goes upto ~800 Mb and then we receive `Server responded with code 0`. So basically, some of the files are not uploaded properly.

We have kept the unicorn `timeout` as 600 in `unicorn.rb`. Can you just suggest what could be wrong in this case, OR at least provide the reference unicorn and nginx configuration settings which works for your setup? It would be a great help!

Thanks
