### ISSUE TITLE
elfinder with ruby 2.1.2 & Rails 4.1.1?

### ISSUE THREAD

**Issue by tilllt** [phallstrom/el_finder#31]
i am a bit lost installing elfinder on rails with recent versions of ruby and rails. is this possible at all?

**Comment by ntt1985** [comment]
SergRain could you give me an example? I'm using elfinder 2.x but i have "Invalid backend response". Thanks

**Comment by SergRain** [comment]
ntt1985 I customize this plugin to work with ckeditor on activeadmin gem, so its different from you may need. The first problem was authenticity token on file upload/ so I just add skip_before_filter to controller. Maybe 'Invalid backend response' shows that you have no folder to scan by plugin?
Can you give more info about error you have?

**Comment by ntt1985** [comment]
I don't know how to read some detailed errors. I need a less complicated documentation (respect to the wiki on github). I think i can solve the problem if i see the error....

**Comment by SergRain** [comment]
any info on rails log? or in browser dev console (maybe on network requests and responses)?

**Comment by coorasse** [comment]
I'm using it on my app with no problems. Just upgraded to Rails 4.1 and Ruby 2.2.
You can have a look into here:
https://github.com/coorasse/Airesis/tree/feature/upgrade_to_rails_4_2

https://github.com/coorasse/Airesis/blob/feature/upgrade_to_rails_4_2/app/controllers/elfinder_controller.rb

https://github.com/coorasse/Airesis/blob/feature/upgrade_to_rails_4_2/app/views/documents/index.html.erb

**Comment by maxivak** [comment]
This gem is written for elfinder 1.1 and it doesn't work with elfinder 2.1.
The format of the returned data differs for elfinder 2.1.
For example, this gem returns JSON with fields:
{
cwd: {...},
cdc: {},
tree: ..
params
}

I checked elfinder 2.1 with the working php connector and the connector returns JSON data as:
{
cwd: {..},
options: {..},
files: [...]
}

It looks like the new version of elfinder 2.1 expects different JSON data from the connector.

So the problem is not connected to the version of Rails or Ruby.

**Comment by phallstrom** [comment]
It's been a long time since I've used el_finder (sorry) but my memory is you have to use the JS translator to make it work.

**Comment by maxivak** [comment]
do you mean using some translator to transform JSON data returned from the controller ?

**Comment by phallstrom** [comment]
This: 

https://github.com/Studio-42/elFinder/wiki/Using-elFinder-2.x-UI-with-1.x-connector

**Comment by maxivak** [comment]
thanks! Looks  promising.. I will check it
